ARG versionNode=20.10.0-alpine3.18
ARG versionNginx=alpine

FROM node:${versionNode} AS build

WORKDIR /app

RUN apk add --no-cache git
RUN git clone https://github.com/fams/guess_game.git ./guess_game

WORKDIR /app/guess_game/frontend

RUN npm install \
    && npm run build

FROM nginx:${versionNginx} AS prod

COPY --from=build /app/guess_game/frontend/build /usr/share/nginx/html
COPY nginx.conf /etc/nginx/nginx.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]