version: '1.0'
services:
  db:
    container_name: database
    restart: always
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secretpass
      POSTGRES_DB: postgres    
    # ports:
    #   - '5432:5432'
    volumes:
      - postgresdata:/var/lib/postgresql/data
  
  back:
    container_name: backend
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.Backend
    environment:
      - FLASK_APP=run.py
      - FLASK_DB_TYPE=postgres
      - FLASK_DB_USER=postgres
      - FLASK_DB_NAME=postgres
      - FLASK_DB_PASSWORD=secretpass
      - FLASK_DB_HOST=db
      - FLASK_DB_PORT=5432
    ports:
      - '5000:5000'
    depends_on:
      - db

  front:
    container_name: frontend
    restart: always  
    build:
      context: .
      dockerfile: Dockerfile.Frontend
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:5000
    ports:
      - '3000:3000'
    depends_on:
      - back

volumes:
  postgresdata: