apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  # replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: adilson90/my-frontend:latest
          env:
            - name: REACT_APP_BACKEND_URL
              value: "http://localhost:32000"
          ports:
            - containerPort: 3000